Push Docker image to AWS ECR added in ci/cd pipeline

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -71,47 +71,47 @@ jobs:
         run: |
           docker push ${{ secrets.DOCKER_HUB_USERNAME }}/emotions:v1
           
-      - name: Deploy to EC2
-        if: success()
-        uses: appleboy/ssh-action@v0.1.5
-        with:
-          host: ${{ secrets.EC2_HOST }}
-          username: ${{ secrets.EC2_USER }}
-          key: ${{ secrets.EC2_SSH_KEY }}
-          # we add ||(i.e. or) true because if script get failed like docker stop my-app then also it not give error and run next script
-          script: |
-            docker stop my-app || true
-            docker rm my-app || true
-            docker system prune -af
-            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/emotions:v1
-            docker run -d \
-              --restart unless-stopped \
-              -p 80:8050 \
-              --name my-app \
-              -e DAGSHUB_PAT=${{ secrets.DAGSHUB_PAT }} \
-              ${{ secrets.DOCKER_HUB_USERNAME }}/emotions:v1            
+#      - name: Deploy to EC2
+#        if: success()
+#        uses: appleboy/ssh-action@v0.1.5
+#        with:
+#          host: ${{ secrets.EC2_HOST }}
+#          username: ${{ secrets.EC2_USER }}
+#          key: ${{ secrets.EC2_SSH_KEY }}
+#          # we add ||(i.e. or) true because if script get failed like docker stop my-app then also it not give error and run next script
+#          script: |
+#            docker stop my-app || true
+#            docker rm my-app || true
+#            docker system prune -af
+#            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/emotions:v1
+#            docker run -d \
+#              --restart unless-stopped \
+#              -p 80:8050 \
+#              --name my-app \
+#              -e DAGSHUB_PAT=${{ secrets.DAGSHUB_PAT }} \
+#              ${{ secrets.DOCKER_HUB_USERNAME }}/emotions:v1
 
-      #      - name: Login to AWS ECR
-#        if: success()
-#        run: |
-#          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
-#          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-#          aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 051826734860.dkr.ecr.ap-southeast-2.amazonaws.com
-#
-#      - name: Build Docker image
-#        if: success()
-#        run: |
-#          docker build -t campusx_ecr .
-#
-#      - name: Tag Docker image
-#        if: success()
-#        run: |
-#          docker tag campusx_ecr:latest 051826734860.dkr.ecr.ap-southeast-2.amazonaws.com/campusx_ecr:latest
-#
-#      - name: Push Docker image to AWS ECR
-#        if: success()
-#        run: |
-#          docker push 051826734860.dkr.ecr.ap-southeast-2.amazonaws.com/campusx_ecr:latest
+      - name: Login to AWS ECR
+        if: success()
+        run: |
+          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws ecr get-login-password --region us-west-2 | sudo docker login --username AWS --password-stdin 376129864263.dkr.ecr.us-west-2.amazonaws.com
+
+      - name: Build Docker image
+        if: success()
+        run: |
+          docker build -t emotions:v1 .
+
+      - name: Tag Docker image
+        if: success()
+        run: |
+          docker tag emotions:v1 376129864263.dkr.ecr.us-west-2.amazonaws.com/mlops-mini-project-registry:latest
+
+      - name: Push Docker image to AWS ECR
+        if: success()
+        run: |
+          docker push 376129864263.dkr.ecr.us-west-2.amazonaws.com/mlops-mini-project-registry:latest
 
 #      # Zip the required files
 #      - name: Zip files for deployment
